/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fronted;

import Backend.AnalizadorLexico;
import Backend.Token;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.StringReader;
import java.util.List;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author gabrielh
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        // Agregar CaretListener para actualizar fila y columna
        jtpEditor.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                actualizarFilaColumna(e);
            }
        });
    }

    private void actualizarFilaColumna(CaretEvent e) {
        try {
            // Obtener la posición del caret en el JTextPane
            int pos = e.getDot(); // Obtener la posición actual del caret

            // Obtener el documento y el texto actual
            Document doc = jtpEditor.getDocument();
            String text = doc.getText(0, doc.getLength());

            // Contar las líneas en el texto
            int lineCount = 0;
            int columnCount = 0;

            // Recorrer el texto hasta la posición del caret para contar líneas y columnas
            for (int i = 0; i < pos; i++) {
                if (text.charAt(i) == '\n') {
                    lineCount++;
                    columnCount = 0; // Reiniciar el contador de columnas en una nueva línea
                } else {
                    columnCount++;
                }
            }

            // Mostrar el número de fila y columna, ambos comenzando desde 0
            filaColumna.setText("Fila: " + lineCount + " Columna: " + columnCount);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtpEditor = new javax.swing.JTextPane();
        jbtAnalizar = new javax.swing.JButton();
        jbtGenerar = new javax.swing.JButton();
        filaColumna = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        subirArchivo = new javax.swing.JMenuItem();
        crearArchivo = new javax.swing.JMenuItem();
        guardarArchivo = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpEditor.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(jtpEditor);

        jbtAnalizar.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jbtAnalizar.setText("Analizar...");
        jbtAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAnalizarActionPerformed(evt);
            }
        });

        jbtGenerar.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jbtGenerar.setText("Generar Diagrama...");
        jbtGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGenerarActionPerformed(evt);
            }
        });

        filaColumna.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        filaColumna.setText("Fila: . Columna: .");

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N

        subirArchivo.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        subirArchivo.setText("Subir archivo...");
        jMenu1.add(subirArchivo);

        crearArchivo.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        crearArchivo.setText("Crear archivo...");
        jMenu1.add(crearArchivo);

        guardarArchivo.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        guardarArchivo.setText("Guardar archivo...");
        jMenu1.add(guardarArchivo);

        guardarComo.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        guardarComo.setText("Guardar como...");
        jMenu1.add(guardarComo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jMenuItem4.setText("Reporte Lexico");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jMenuItem5.setText("Reporte Sintactico");
        jMenu2.add(jMenuItem5);

        jMenuItem1.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jMenuItem1.setText("Reporte de tablas");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jMenuItem2.setText("Reporte de tablas modificadas");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Liberation Serif", 0, 15)); // NOI18N
        jMenuItem3.setText("Reporte de operaciones");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(filaColumna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAnalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filaColumna)
                    .addComponent(jbtGenerar)
                    .addComponent(jbtAnalizar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtGenerarActionPerformed

    private void jbtAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAnalizarActionPerformed
        // TODO add your handling code here:
        analizar();
    }//GEN-LAST:event_jbtAnalizarActionPerformed

    public void analizar() throws BadLocationException {
        String entrada = jtpEditor.getText();
        AnalizadorLexico analizadorLexico = new AnalizadorLexico(new StringReader(entrada));
        StyledDocument doc = jtpEditor.getStyledDocument();

        // Eliminar el contenido anterior
        doc.remove(0, doc.getLength());

        try {
            while (analizadorLexico.yylex() != AnalizadorLexico.YYEOF) {
                // Aquí deberías implementar la lógica para obtener el token y su tipo
                // por ejemplo:
                Token token = ... // Obtener el token desde el analizador
                String tokenText = token.getText(); // Asumiendo que hay un método para obtener el texto del token

                // Aplicar estilo basado en el tipo de token
                aplicarEstilo(doc, tokenText, token.getTipo()); // Método que aplicarás a continuación
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void aplicarEstilo(StyledDocument doc, String tokenText, String tipo) {
        // Definir estilos
        Style style = jtpEditor.addStyle("TokenStyle", null);

        switch (tipo) {
            case "ENTERO":
                StyleConstants.setForeground(style, Color.BLUE);
                break;
            case "DECIMAL":
                StyleConstants.setForeground(style, Color.GREEN);
                break;
            case "CADENA":
                StyleConstants.setForeground(style, Color.RED);
                break;
            case "COMENTARIO":
                StyleConstants.setForeground(style, Color.GRAY);
                break;
            case "IDENTIFICADOR":
                StyleConstants.setForeground(style, Color.MAGENTA);
                break;
            // Agrega más casos según tus tipos de tokens
            default:
                StyleConstants.setForeground(style, Color.BLACK); // Color por defecto
                break;
        }

        // Insertar el token en el documento con el estilo correspondiente
        try {
            int offset = doc.getLength();
            doc.insertString(offset, tokenText + " ", style); // Insertar el token con un espacio
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem crearArchivo;
    private javax.swing.JLabel filaColumna;
    private javax.swing.JMenuItem guardarArchivo;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAnalizar;
    private javax.swing.JButton jbtGenerar;
    private javax.swing.JTextPane jtpEditor;
    private javax.swing.JMenuItem subirArchivo;
    // End of variables declaration//GEN-END:variables
}
